// resources/js/pages/CheatSheet/Links.vue
<script setup lang="ts">
import CheatSheetLayout from '@/layouts/CheatSheetLayout.vue';
import { ExternalLink } from 'lucide-vue-next';

defineProps<{
    pageTitle: string;
    links: Array<{ text: string; url: string }>;
}>();
</script>

<template>
    <CheatSheetLayout :page-title="pageTitle">
        <div class="space-y-6">
            <div class="prose prose-invert max-w-none">
                <p class="text-neutral-400">
                    Useful external resources for guides, tier lists, and tools.
                </p>
            </div>

            <div class="grid gap-4 md:grid-cols-2">
                <a
                    v-for="(link, i) in links"
                    :key="i"
                    :href="link.url"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="group flex items-center justify-between rounded-xl border border-neutral-800 bg-neutral-900 p-4 transition-all hover:border-pink-500/50 hover:bg-neutral-800/50"
                >
                    <span
                        class="font-medium text-neutral-200 transition-colors group-hover:text-white"
                    >
                        {{ link.text }}
                    </span>
                    <ExternalLink
                        :size="18"
                        class="ml-4 shrink-0 text-neutral-500 transition-colors group-hover:text-pink-400"
                    />
                </a>
            </div>
        </div>
    </CheatSheetLayout>
</template>

// app/links/page.tsx
import type { Metadata } from "next";
import PageLayout from "../components/PageLayout";

export const metadata: Metadata = {
  title: "Links",
};
import { getLinks } from "../lib/data";
import { ExternalLinkIcon } from "../components/Icons";

export default async function LinksPage() {
  const links = await getLinks();

  return (
    <PageLayout title="Links">
      <div className="space-y-6">
        <div className="prose prose-invert max-w-none">
          <p className="text-neutral-400">Useful external resources for guides, tier lists, and tools.</p>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          {links.map((link: any, index: number) => (
            <a
              key={index}
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-between p-4 bg-neutral-900 rounded-xl border border-neutral-800 hover:border-pink-500/50 hover:bg-neutral-800/50 transition-all group"
            >
              <span className="font-medium text-neutral-200 group-hover:text-white transition-colors">{link.text}</span>
              <ExternalLinkIcon className="text-neutral-500 group-hover:text-pink-400 transition-colors shrink-0 ml-4" />
            </a>
          ))}
        </div>
      </div>
    </PageLayout>
  );
}
