// app/races/page.tsx
import type { Metadata } from "next";
import PageLayout from "../components/PageLayout";

export const metadata: Metadata = {
  title: "Races",
};
import { getRaces } from "../lib/data";
import { CalendarIcon } from "../components/Icons";

export default async function RacesPage() {
  const races = await getRaces();

  return (
    <PageLayout title="Races">
      <div className="space-y-8">
        <div className="prose prose-invert max-w-none">
          <p className="text-neutral-400">Key races to target for the "URA Finale" scenario.</p>
        </div>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {races.map((yearGroup: any, index: number) => (
            <div key={index} className="bg-neutral-900 rounded-xl border border-neutral-800 overflow-hidden">
              <div className="p-4 bg-neutral-800/50 border-b border-neutral-800 flex items-center gap-3">
                <CalendarIcon className="text-pink-400" />
                <h3 className="font-semibold text-lg text-white">{yearGroup.year}</h3>
              </div>
              <div className="p-4 space-y-3">
                {yearGroup.races.map((race: any, i: number) => (
                  <div key={i} className="flex justify-between items-start group hover:bg-neutral-800/50 p-2 rounded-lg transition-colors -mx-2">
                    <div className="space-y-0.5">
                      <span className="font-medium text-neutral-200 block group-hover:text-pink-300 transition-colors">{race.name}</span>
                      {race.note && <span className="text-xs text-neutral-500 block">{race.note}</span>}
                    </div>
                    <span className="text-sm text-neutral-500 font-mono whitespace-nowrap bg-neutral-950 px-2 py-1 rounded">
                      {race.time}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </PageLayout>
  );
}

// resources/js/pages/CheatSheet/Races.vue
<script setup lang="ts">
import CheatSheetLayout from '@/layouts/CheatSheetLayout.vue';
import { Calendar } from 'lucide-vue-next';

type Race = {
    name: string;
    time: string;
    note?: string;
    optional?: boolean;
};

type YearGroup = {
    year: string;
    races: Race[];
};

defineProps<{
    pageTitle: string;
    races: YearGroup[];
}>();
</script>

<template>
    <CheatSheetLayout :page-title="pageTitle">
        <div class="space-y-8">
            <div class="prose prose-invert max-w-none">
                <p class="text-neutral-400">
                    Key races to target for the "URA Finale" scenario.
                </p>
            </div>

            <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                <div
                    v-for="yearGroup in races"
                    :key="yearGroup.year"
                    class="overflow-hidden rounded-xl border border-neutral-800 bg-neutral-900"
                >
                    <div
                        class="flex items-center gap-3 border-b border-neutral-800 bg-neutral-800/50 p-4"
                    >
                        <Calendar :size="20" class="text-pink-400" />
                        <h3 class="text-lg font-semibold text-white">
                            {{ yearGroup.year }}
                        </h3>
                    </div>
                    <div class="space-y-3 p-4">
                        <div
                            v-for="race in yearGroup.races"
                            :key="race.name"
                            class="group -mx-2 flex items-start justify-between rounded-lg p-2 transition-colors hover:bg-neutral-800/50"
                        >
                            <div class="space-y-0.5">
                                <span
                                    class="block font-medium text-neutral-200 transition-colors group-hover:text-pink-300"
                                >
                                    {{ race.name }}
                                </span>
                                <span
                                    v-if="race.note"
                                    class="block text-xs text-neutral-500"
                                >
                                    {{ race.note }}
                                </span>
                            </div>
                            <span
                                class="rounded bg-neutral-950 px-2 py-1 font-mono text-sm whitespace-nowrap text-neutral-500"
                            >
                                {{ race.time }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </CheatSheetLayout>
</template>
